apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: reporting
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: reporting
      name: spp-aws-key
      version: latest
      property: spp-aws-key
    - key: reporting
      name: spp-aws-secret
      version: latest
      property: spp-aws-secret