apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.ingress.enabled }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"responses-dashboard-backend-config"}}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
