env: minikube
namespace: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      cpu: "200m"
      memory: "350Mi"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      cpu: "100m"
      memory: "256Mi"


autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 150
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

database:
  sqlProxyEnabled: false
  managedPostgres: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

dns:
  enabled: false
  wellKnownPort: 8080
