env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "500Mi"
    cpu: "10m"
  limits:
    cpu: "50m"
    memory: "1000Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 250
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

database:
  sqlProxyEnabled: false
  managedPostgres: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

crons:
  sppReportScheduler:
    name: rm-reporting-spp-reporting-scheduler
    cron: "0 23 * * *"
    target: "spp-reporting-api/v1/spp-reporting/send-report"

gcp:
  project: ras-rm-dev
  bucket: ras-rm-spp-report-dev

aws:
  enabled: false