env: performance

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      cpu: "50m"
      memory: "125Mi"
    limits:
      cpu: "200m"
      memory: "350Mi"
  proxy:
    requests:
      cpu: "10m"
      memory: "25Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"


autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 250
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

database:
  sqlProxyEnabled: true
  managedPostgres: true
  secrets:
    usernameKey: reporting-username
    passwordKey: reporting-password
    nameKey: reporting-db-name
    caseUserNameKey: case-username
    casePasswordKey: case-password
    caseNameKey: case-db-name
    partyUserNameKey: party-username
    partyPasswordKey: party-password
    partyNameKey: party-db-name
