env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

ingress:
  enabled: false

database:
  sqlProxyEnabled: false
  managedPostgres: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

resources:
  requests:
    memory: "256Mi"