env: minikube

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      cpu: "50m"
      memory: "125Mi"
    limits:
      cpu: "200m"
      memory: "350Mi"
  proxy:
    requests:
      cpu: "10m"
      memory: "25Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"


autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 250
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

database:
  sqlProxyEnabled: false
  managedPostgres: false
  secrets:
    caseUserNameKey: username
    casePasswordKey: password
    caseNameKey: db-name
    partyUserNameKey: username
    partyPasswordKey: password
    partyNameKey: db-name
